max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
indent_style = "Block"
format_strings = false
wrap_comments = false
comment_width = 80
normalize_comments = false
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_indent = "Visual"
imports_layout = "Mixed"
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imports = true
reorder_imported_names = true
reorder_modules = true
space_before_colon = false
space_after_colon = true
spaces_within_parens_and_brackets = false
struct_field_align_threshold = 0
remove_blank_lines_at_start_or_end_of_block = true
fn_args_density = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_comma = "Vertical"
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
merge_derives = true
use_try_shorthand = false
condense_wildcard_suffixes = false
force_explicit_abi = true
write_mode = "Overwrite"
disable_all_formatting = false
skip_children = false
hide_parse_errors = false
report_todo = "Never"
report_fixme = "Never"
